### ISSUE TITLE
Setup fails on Python 3.14 / HA 2026.7: 'ClientTlsContext' object has no attribute '_certificate_source' (awscrt IoT-metrics)

### ISSUE THREAD

**Issue by jaydek89** [dahlb/ha_hatch#323]
### System Health details

System Information
version                | core-2026.7.4
installation_type      | Home Assistant OS
python_version         | 3.14.6
os_name                | Linux
os_version             | 6.18.35-haos
arch                   | x86_64
timezone               | America/New_York
Home Assistant Supervisor
host_os                | Home Assistant OS 18.0
supervisor             | 2026.07.3
docker_version         | 29.5.3
chassis                | vm
Integration
ha_hatch               | 1.31.2
hatch_rest_api         | 1.34.0
Device                 | Hatch Rest (2nd gen), WiFi

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_hatch/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

On Home Assistant 2026.7.4 (Python 3.14.6), the integration fails to set up and stays in `setup_retry`. The config entry is created fine (credentials accepted), but the data coordinator's first update fails while building the AWS IoT MQTT connection:

```
AttributeError: 'ClientTlsContext' object has no attribute '_certificate_source'
```

The failure is in `awscrt`'s IoT-metrics code — `awscrt/mqtt.py` line 421 in `MqttClientConnection.__init__` calls `_certificate_source_metrics_value(tls_ctx._certificate_source)`, and the loaded native `ClientTlsContext` has no `_certificate_source` attribute. This is consistent with the awscrt Python wrapper and the native `_awscrt` extension being at mismatched versions on Python 3.14 (no `cp314` wheels are published; pip falls back to the `cp313`-abi3 wheel).

This looks like a **new symptom of the same class of bug as #293** ("function takes exactly 17 arguments (18 given)" on HA 2026.4 / Python 3.14), which was fixed in #297. That fix resolved the `mqtt_client_connection_connect` arity mismatch, but on the current versions (HA 2026.7.4, ha_hatch 1.31.2, hatch_rest_api 1.34.0) awscrt now fails a bit earlier — at TLS-context/metrics setup — with the missing `_certificate_source` attribute instead.

Secondary effect (same as noted in #293): repeated retries hit `https://data.hatchbaby.com/public/v1/login` and the Hatch account gets rate-limited (HTTP 429), after which the coordinator backs off (`Retrying in 600 seconds`). Credentials are valid — this is not an auth problem.

### Reproduction steps

1. On HA 2026.7.x (Python 3.14), install the integration via HACS and configure with valid Hatch credentials.
2. The config entry is created; setup proceeds to the first coordinator update.
3. Setup fails with the `_certificate_source` `AttributeError` (see logs below) and enters `setup_retry`.
4. Repeated retries eventually trigger a 429 from the Hatch login endpoint.

### Debug logs

```text
Captured with DEBUG logging enabled for `custom_components.ha_hatch`, `hatch_rest_api`, and `awscrt` (excerpt; timestamps are the HA host's local time):


ERROR (MainThread) [custom_components.ha_hatch.hatch_data_update_coordinator] 'ClientTlsContext' object has no attribute '_certificate_source'
Traceback (most recent call last):
  File "/config/custom_components/ha_hatch/hatch_data_update_coordinator.py", line 244, in _async_update_data
  File "/usr/local/lib/python3.14/site-packages/hatch_rest_api/util_bootstrap.py", line 80, in get_rest_devices
  File "/usr/local/lib/python3.14/site-packages/awscrt/mqtt.py", line 421, in __init__
    val = _certificate_source_metrics_value(tls_ctx._certificate_source)
AttributeError: 'ClientTlsContext' object has no attribute '_certificate_source'

The above exception was the direct cause of the following exception:
homeassistant.helpers.update_coordinator.UpdateFailed: 'ClientTlsContext' object has no attribute '_certificate_source'

The above exception was the direct cause of the following exception:
homeassistant.exceptions.ConfigEntryNotReady: 'ClientTlsContext' object has no attribute '_certificate_source'

INFO (MainThread) [custom_components.ha_hatch] Config entry 'jhaydekmail@gmail.com' for ha_hatch integration not ready yet: 'ClientTlsContext' object has no attribute '_certificate_source'; Retrying in 600 seconds


Followed on subsequent retries by:


WARNING [hatch_rest_api.hatch] Rate limited (429) for URL: https://data.hatchbaby.com/public/v1/login
hatch_rest_api.errors.RateError: API rate limit exceeded. Please wait before retrying.
```

**Comment by Nickfost** [comment]
Confirming this remains reproducible on the latest release. Home Assistant OS is running Core 2026.7.4 on Python 3.14 with ha_hatch 1.31.3, hatch_rest_api 1.34.1, awsiotsdk 1.31.0, and awscrt 0.36.1. The coordinator fails with the same `ClientTlsContext` `_certificate_source` AttributeError while constructing the AWS IoT MQTT connection. I observed identical failures approximately 10 minutes apart. Home Assistant and unrelated integrations remain healthy, but the Hatch entities cannot refresh reliably.

**Comment by 0xskynet** [comment]
Same issue after updating HA 2026.7.4

**Comment by jaydek89** [comment]
Resolved by **ha_hatch v1.31.4**, which bumps the pin to **hatch_rest_api 1.34.2** (containing #71 — disabling the AWS IoT SDK metrics path so the `tls_ctx._certificate_source` read is never hit).

Confirmed fixed on my setup: HA 2026.7.4 / Python 3.14.6, HAOS 18.0. After updating to 1.31.4 and restarting Home Assistant, the config entry loads cleanly, both Hatch Rest devices and their entities are present and reporting live state, and there are no more `_certificate_source` errors in the log.

Thanks @chasebolt for the root-cause analysis (in-process awscrt module skew) and the fix, and @dahlb for the quick dependency bump. Closing.
